backendpro/Modulo Ruby on Rails/config/routes.rb
Rails.application.routes.draw do

  resources :awards, :except => [:new, :edit]
  resources :songs, :movies, :stars
end

backendpro/Modulo Ruby on Rails/app/models/award.rb
class Award < ActiveRecord::Base
	belongs_to :winnable, polymorphic: :true
	validates :year, numericality: {greater_than: 1800, less_than: 2015}
end

backendpro/Modulo Ruby on Rails/app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :performances
  has_many :stars, through: :performances	
  has_and_belongs_to_many :songs
  has_many :awards, as: :winnable

  validates :title, presence: :true, uniqueness: true
  validates :release_year, numericality: {greater_than: 1800, less_than: 2015}
end

backendpro/Modulo Ruby on Rails/app/models/performance.rb
class Performance < ActiveRecord::Base
  belongs_to :movie
  belongs_to :star

  validates_associated :star
  validates_associated :movie
end

backendpro/Modulo Ruby on Rails/app/models/song.rb
class Song < ActiveRecord::Base
  has_and_belongs_to_many :movies
end

backendpro/Modulo Ruby on Rails/app/models/star.rb
class Star < ActiveRecord::Base
  has_many :performances
  has_many :movies, through: :performances	
  has_many :awards, as: :winnable

  validates :name, presence: true
end

backendpro/Modulo Ruby on Rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  respond_to :json

  rescue_from(ActiveRecord::RecordInvalid) do |invalid|
  	response = {status: 'error', 
  		        fields: invalid.record.errors}
  	render json: response, status: :unprocessable_entity
  end

  rescue_from(ActiveRecord::RecordNotFound) do |invalid|
  	response = {status: 'error', 
  		        fields: 'registro inexistente'}
  	render json: response, status: :unprocessable_entity
  end  

end

backendpro/Modulo Ruby on Rails/app/controllers/awards_controller.rb
class AwardsController < ApplicationController
	def index
		@awards = Award.all.order(:year)
		respond_with @awards
	end

	def show
		@award = Award.find params[:id]
		respond_with @award
	end

	def create
		@award = Award.new award_params
		if @award.save!
			respond_with @award, status: :created, location: @award
		else
			respond_with @awards.errors, status: :unprocessable_entity
		end
	end

	def update
		@award = Award.find params[:id]
		if @award.update_attributes!(award_params)
			respond_with @award, status: :ok, location: @award
		else
			respond_with @awards.errors, status: :unprocessable_entity
		end
	end

	def destroy
		@award = Award.find params[:id]
		if @award.destroy
			render json: {status: :ok}		
		else
			respond_with @awards.errors, status: :unprocessable_entity	
		end
	end

	protected
	def award_params
		params.require(:award).permit(:name, :category, :year)
	end
end

backendpro/Modulo Ruby on Rails/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all.includes(:stars)
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params[:movie]
    end
end

backendpro/Modulo Ruby on Rails/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params[:song]
    end
end

backendpro/Modulo Ruby on Rails/app/controllers/stars_controller.rb
class StarsController < ApplicationController
  before_action :set_star, only: [:show, :edit, :update, :destroy]

  # GET /stars
  # GET /stars.json
  def index
    @stars = Star.all
  end

  # GET /stars/1
  # GET /stars/1.json
  def show
  end

  # GET /stars/new
  def new
    @star = Star.new
  end

  # GET /stars/1/edit
  def edit
  end

  # POST /stars
  # POST /stars.json
  def create
    @star = Star.new(star_params)

    respond_to do |format|
      if @star.save
        format.html { redirect_to @star, notice: 'Star was successfully created.' }
        format.json { render :show, status: :created, location: @star }
      else
        format.html { render :new }
        format.json { render json: @star.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stars/1
  # PATCH/PUT /stars/1.json
  def update
    respond_to do |format|
      if @star.update(star_params)
        format.html { redirect_to @star, notice: 'Star was successfully updated.' }
        format.json { render :show, status: :ok, location: @star }
      else
        format.html { render :edit }
        format.json { render json: @star.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stars/1
  # DELETE /stars/1.json
  def destroy
    @star.destroy
    respond_to do |format|
      format.html { redirect_to stars_url, notice: 'Star was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_star
      @star = Star.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def star_params
      params[:star]
    end
end

backendpro/Modulo Ruby on Rails/app/helpers/application_helper.rb
module ApplicationHelper
end

backendpro/Modulo Ruby on Rails/app/helpers/awards_helper.rb
module AwardsHelper
end

backendpro/Modulo Ruby on Rails/app/helpers/movies_helper.rb
module MoviesHelper
end

backendpro/Modulo Ruby on Rails/app/helpers/songs_helper.rb
module SongsHelper
end

backendpro/Modulo Ruby on Rails/app/helpers/stars_helper.rb
module StarsHelper
end

backendpro/Modulo Ruby on Rails/app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

backendpro/Modulo Ruby on Rails/app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

backendpro/Modulo Ruby on Rails/app/views/songs/index.html.erb
<h1>Listing songs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>

backendpro/Modulo Ruby on Rails/app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

backendpro/Modulo Ruby on Rails/app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>

backendpro/Modulo Ruby on Rails/app/views/stars/_form.html.erb
<%= form_for(@star) do |f| %>
  <% if @star.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@star.errors.count, "error") %> prohibited this star from being saved:</h2>

      <ul>
      <% @star.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

backendpro/Modulo Ruby on Rails/app/views/stars/edit.html.erb
<h1>Editing star</h1>

<%= render 'form' %>

<%= link_to 'Show', @star %> |
<%= link_to 'Back', stars_path %>

backendpro/Modulo Ruby on Rails/app/views/stars/index.html.erb
<h1>Listing stars</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stars.each do |star| %>
      <tr>
        <td><%= link_to 'Show', star %></td>
        <td><%= link_to 'Edit', edit_star_path(star) %></td>
        <td><%= link_to 'Destroy', star, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Star', new_star_path %>

backendpro/Modulo Ruby on Rails/app/views/stars/new.html.erb
<h1>New star</h1>

<%= render 'form' %>

<%= link_to 'Back', stars_path %>

backendpro/Modulo Ruby on Rails/app/views/stars/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_star_path(@star) %> |
<%= link_to 'Back', stars_path %>